# Generated by Django 4.2.6 on 2023-10-12 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_messages_deviceid_alter_chatroom_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messages",
            old_name="message",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="messages",
            old_name="deviceId",
            new_name="device_id",
        ),
    ]
